In [38]:
import numpy as np
import matplotlib.pyplot as pp
#data = pd.read_csv("good2.csv").to_dict(orient="row")
#cancer_df=pd.DataFrame(data,columns=cancer.feature_names)


# CSV file
#csv_file = ("bad.csv")
# read cvs with pandas read_csv
#data = pd.read_csv(csv_file)

#data = np.genfromtxt("good.csv", dtype=float, delimiter=',') 

data=np.loadtxt("good.txt",dtype=float,skiprows=0,usecols=range(0,21))




#data_df=pd.DataFrame(data,columns=feature_names)
print(data)

#malignant=data[good==0]
#benign=data[good==1]

[[2.130e+01 1.000e+00 3.500e+01 ... 2.737e+03 8.000e-02 4.312e+03]
 [8.300e+00 0.000e+00 9.800e+01 ... 1.325e+03 2.800e-01 8.771e+03]
 [2.770e+01 2.000e+00 4.000e+00 ... 5.280e+02 8.500e-01 6.132e+03]
 ...
 [2.600e+00 1.000e+00 1.600e+01 ... 9.420e+02 5.900e-01 1.601e+03]
 [8.200e+00 2.000e+00 1.010e+02 ... 1.878e+03 3.300e-01 8.262e+03]
 [2.450e+01 0.000e+00 4.000e+01 ... 2.958e+03 7.000e-02 4.595e+03]]


In [39]:
from sklearn.model_selection import train_test_split
from matplotlib.pyplot import matplotlib
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

import matplotlib.pyplot as plt 
import numpy as np
import seaborn as sns
import pandas as pd

In [40]:
scaler = StandardScaler() # standardized feature by removing mean and scaled to unit variance 
scaler.fit(data)

X_scaled = scaler.transform(data)


print (X_scaled.min(axis=0))




[-1.30074305 -1.27295762 -1.77097151 -1.60218208 -1.19576018 -1.62733199
 -1.89839499 -1.928404   -1.0392354  -1.429834   -1.80158472 -1.5920363
 -2.20055967 -1.80806725 -1.77754306 -0.80363756 -1.2780193  -1.81391164
 -1.509033   -1.49525682 -1.96249227]


In [46]:
n_components=3
pca = PCA(n_components=n_components) # instantiate the PCA and keep the first n components
pca.fit(X_scaled)
# now transform 

x_pca=pca.transform(X_scaled)

# check the shape 

print (x_pca.shape)
#print pca.explained_variance

ex_variance=np.var(x_pca,axis=0)

ex_variance_rat=ex_variance/np.sum(ex_variance)

print (ex_variance_rat)



(79, 3)
[0.39151707 0.3264084  0.28207453]


In [47]:
#This is how you generate samples:
#First, sample in the PCA latent space, i.e., coordinates along the principal axis vectors
nSamples=20
latentMean=np.zeros(n_components)
latentStd=np.sqrt(ex_variance)
latent=np.random.normal(latentMean,latentStd,[nSamples,n_components])
#print(latent)
#Now, we can convert back to the original space
sampled=pca.inverse_transform(latent)
print(sampled)

[[-4.63941643e-01  4.97258412e-01 -5.69585779e-02 -2.98307299e-01
  -1.02771355e-01 -4.44245542e-01 -7.61342282e-01  3.57777078e-01
  -6.61314426e-02  5.52625264e-01 -4.42299555e-01 -5.02304812e-01
   7.09630349e-01  2.37261937e-01  4.03940396e-01  1.34814888e-01
  -3.71819142e-01 -7.22975539e-02 -7.10241798e-02 -6.75255931e-01
   2.17182633e-01]
 [ 1.22021631e-01  3.74176864e-01 -9.81053511e-02 -5.74863765e-01
   5.08632118e-01  4.25085662e-01 -7.12174327e-02 -3.30501130e-01
  -4.22653525e-01  2.19937001e-01 -2.33852642e-01  2.19755736e-01
  -1.24480252e-01  1.75040999e-01 -2.09049428e-01  6.45319346e-01
   6.53976779e-01 -1.09668601e-01  8.31813861e-02  2.58499238e-01
   2.93723288e-02]
 [ 8.39161587e-01 -9.74326133e-01 -4.76528708e-02 -3.37088805e-02
   6.48564254e-01  1.07517494e+00  8.16022731e-01  3.68260229e-02
   5.87209199e-02 -1.22184337e+00  1.08414707e+00  2.17884210e-01
  -1.27525261e+00  4.84131737e-01 -5.38617301e-01  3.68095610e-02
   2.75591122e-01 -2.36054786e-01  6.4

In [43]:
new=scaler.inverse_transform(sampled)	
print(new)

[[ 1.28711122e+01  1.91007823e+00  8.77256729e+01  5.54517285e-01
   1.77013708e+00  6.77988297e-01  4.08092081e-01  5.23087894e-01
   2.94217159e-01  4.89404749e-01  3.73195671e+03  2.52464467e+00
   5.48903386e-01  7.34517010e-01  4.48917640e-01  9.48168407e-01
   9.58616407e-01  1.68319354e+03  1.79803209e+03  4.27752407e-01
   6.77800288e+03]
 [ 6.64536368e+00  1.67629541e+00  1.12509104e+02  8.45935798e-01
   1.49674017e-01  1.66500291e-01  5.35978729e-01  4.77581307e-01
   1.06604180e+00  6.17465042e-01  2.81911402e+03  2.99774808e+00
   7.80501873e-01  2.43165925e-01  5.83077825e-01  7.27686986e-02
   4.37934144e-01  2.66376087e+03  7.26147547e+02  5.00937132e-01
   4.25050014e+03]
 [ 1.24090903e+01  1.85465334e+00  9.98976540e+01  6.82741671e-01
   1.18711092e+00  5.43064735e-01  5.99290819e-01  3.39747448e-01
   4.78984694e-01  5.42280449e-01  3.18846700e+03  3.70836110e+00
   5.60457868e-01  4.27152818e-01  4.11500603e-01  6.68082387e-01
   1.05736091e+00  2.23508115e+03  1.2

In [48]:
np.savetxt('patch.txt', new, fmt='%f', newline=';')